version: '2'
services:
    db:
        image: mysql:5.7
        environment:
            - MYSQL_ROOT_PASSWORD=secret
            - MYSQL_DATABASE=revel
            - MYSQL_USER=revel
            - MYSQL_PASSWORD=secret
        volumes:
            - ./datadir:/var/lib/mysql
    web:
#        build: . 
        image: goody80/go_revel:0.1
        volumes:
            - ./myapp:/go/src/myapp 
        entrypoint: revel run myapp 
        ports:
            - 9000:9000 
#        depends_on:
        links:
            - db 
        environment:
            - APP_NAME=RalfApp
            - APP_PORT=9000
            - APP_DB=revel
            - APP_DB_PW=secret
#volumes:
#    db_data:
#      driver: local
